# add markdown viewer
#
#  - [issues/2824](https://github.com/helix-editor/helix/issues/2824)
#  cargo install --git https://github.com/euclio/mdpls
#
#  ```shell
#  $ cat ~/.config/helix/languages.toml
#  ```

[[language]]
name = "markdown"
language-server = { command = "mdpls" }
config = {  markdown.preview.auto = true,  markdown.preview.browser = "open" }

[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
